data_path: data/data_EXP_100kEvents
results_dir: results
model: wgan
ws_params:
  alpha_min: 0.8
  alpha_max: 1.0
  alpha_step: 0.01
aging:
  function: xyz
  af_min: 0.8
  af_max: 1.0
  sigma: 0.0
  noise_seed: 42
  n_events: 50000
  use_test_dataset: false
  test_fraction: 0.2
  independent_event_sampling: true
  new_events_seed: 44
  old_events_seed: 67
  ensure_non_overlap: false
  event_col: event
  x_col: x
  y_col: y
  z_col: z
  energy_col: E
plots:
  energy_distribution:
    quantile: 0.95
    bins: 150
    filename: energy_distribution.png
    dpi: 150
  aging_vs_frequency:
    xlim: null
    filename: aging_vs_frequency.png
    dpi: 150
  aging_correlations:
    columns:
    - aging
    - x
    - y
    - z
    - freq
    filename: aging_correlations.png
    figsize:
    - 7
    - 5
    dpi: 150
  global_shift_hist:
    quantile: 0.8
    kde: false
    filename: global_shift_hist.png
    dpi: 150
  global_energy_shift:
    filename: global_energy_shift.png
    dpi: 150
  energy_distribution_cell:
    cell_idx: null
    quantile: 0.99
    filename: energy_distribution_cell.png
    dpi: 150
  spatial_distribution:
    x_min: -60
    x_max: 60
    y_min: -60
    y_max: 60
    z_min: -125
    z_max: -50
    dpi: 150
  cell_activity_distribution:
    figsize:
    - 6
    - 4
    bins: 50
    filename: distribution_of_cell_activity_per_event.png
    dpi: 150
  aging_factor_xy:
    z_fixed: -90.0
    n_events: 1000000
    filename: aging_factor_xy.png
    dpi: 150
  aging_factor_z:
    x_fixed: 0
    y_fixed: 0
    n_events: 1000000
    filename: aging_factor_z.png
    dpi: 150
  energy_histogram_cell:
    cell_key: null
    filename: energy_histogram_cell.png
    dpi: 150
wgan_params:
  use_gradient_penalty: true
  gp_lambda: 10.0
  clip_value: 0.01
  use_energy_mask: true
  energy_cuts:
    enabled: true
    new_min: 200
    old_min: 200
  batch_size: 2048
  epochs: 50
  lr: 0.0002
  betas:
  - 0.5
  - 0.999
  seed: 42
  use_scheduler_g: false
  use_scheduler_d: false
  scheduler_g: ReduceLROnPlateau
  scheduler_d: ReduceLROnPlateau
  filter:
    x_range:
    - -30
    - 30
    y_range:
    - -30
    - 30
    z_range:
    - -100
    - -80
  logs_dir: logs
  models_dir: models
  save_best_model: true
  save_every_n_epochs: 10
